# Generated by Django 2.1.5 on 2019-02-01 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя разработчика')),
                ('rank_position', models.CharField(choices=[('intern', 'Intern'), ('teamlead', 'Team Lead'), ('none', 'None'), ('senior', 'Senior'), ('arch', 'Arch'), ('techlead', 'Tech Lead'), ('middle', 'Middle'), ('junior', 'Junior')], default='none', max_length=20, verbose_name='Уровень')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Должность')),
                ('profile_link', models.URLField(null=True)),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('step_recruit', models.CharField(choices=[('вакансия закрыта', 'Вакансия закрыта'), ('свободен', 'Свободен'), ('резюме отправлено', 'Резюме отправлено'), ('контакт', 'Контакт')], default='свободен', max_length=40, verbose_name='Этап рекрутинга')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peopleDB.City', verbose_name='Город')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peopleDB.Country', verbose_name='Страна')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Навыки')),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peopleDB.Country'),
        ),
    ]
