# Generated by Django 2.1.5 on 2019-02-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('arch', 'Arch'), ('junior', 'Junior'), ('middle', 'Middle'), ('techlead', 'Tech Lead'), ('none', 'None'), ('senior', 'Senior'), ('intern', 'Intern'), ('teamlead', 'Team Lead')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('контакт', 'Контакт'), ('вакансия закрыта', 'Вакансия закрыта'), ('резюме отправлено', 'Резюме отправлено'), ('свободен', 'Свободен')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
