# Generated by Django 2.1.5 on 2019-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0002_auto_20190201_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('arch', 'Arch'), ('senior', 'Senior'), ('none', 'None'), ('intern', 'Intern'), ('middle', 'Middle'), ('junior', 'Junior'), ('techlead', 'Tech Lead'), ('teamlead', 'Team Lead')], default='none', max_length=20, verbose_name='Уровень'),
        ),
    ]
