# Generated by Django 2.1.5 on 2019-02-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0003_auto_20190201_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('teamlead', 'Team Lead'), ('none', 'None'), ('senior', 'Senior'), ('intern', 'Intern'), ('techlead', 'Tech Lead'), ('arch', 'Arch'), ('junior', 'Junior'), ('middle', 'Middle')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('свободен', 'Свободен'), ('резюме отправлено', 'Резюме отправлено'), ('контакт', 'Контакт'), ('вакансия закрыта', 'Вакансия закрыта')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
