# Generated by Django 2.1.5 on 2019-02-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0004_auto_20190201_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('junior', 'Junior'), ('none', 'None'), ('techlead', 'Tech Lead'), ('senior', 'Senior'), ('teamlead', 'Team Lead'), ('intern', 'Intern'), ('arch', 'Arch'), ('middle', 'Middle')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('контакт', 'Контакт'), ('вакансия закрыта', 'Вакансия закрыта'), ('резюме отправлено', 'Резюме отправлено'), ('свободен', 'Свободен')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
