# Generated by Django 2.1.5 on 2019-02-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0007_auto_20190201_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior'), ('middle', 'Middle'), ('none', 'None'), ('intern', 'Intern'), ('arch', 'Arch'), ('techlead', 'Tech Lead'), ('teamlead', 'Team Lead')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('контакт', 'Контакт'), ('свободен', 'Свободен'), ('вакансия закрыта', 'Вакансия закрыта'), ('резюме отправлено', 'Резюме отправлено')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
