# Generated by Django 2.1.5 on 2019-02-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0008_auto_20190201_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('senior', 'Senior'), ('middle', 'Middle'), ('none', 'None'), ('arch', 'Arch'), ('junior', 'Junior'), ('teamlead', 'Team Lead'), ('intern', 'Intern'), ('techlead', 'Tech Lead')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('вакансия закрыта', 'Вакансия закрыта'), ('контакт', 'Контакт'), ('свободен', 'Свободен'), ('резюме отправлено', 'Резюме отправлено')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
