# Generated by Django 2.1.5 on 2019-02-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0009_auto_20190201_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('intern', 'Intern'), ('middle', 'Middle'), ('arch', 'Arch'), ('junior', 'Junior'), ('techlead', 'Tech Lead'), ('none', 'None'), ('teamlead', 'Team Lead'), ('senior', 'Senior')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('резюме отправлено', 'Резюме отправлено'), ('вакансия закрыта', 'Вакансия закрыта'), ('свободен', 'Свободен'), ('контакт', 'Контакт')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
