# Generated by Django 2.1.5 on 2019-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0010_auto_20190208_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('arch', 'Arch'), ('junior', 'Junior'), ('senior', 'Senior'), ('intern', 'Intern'), ('middle', 'Middle'), ('techlead', 'Tech Lead'), ('none', 'None'), ('teamlead', 'Team Lead')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('резюме отправлено', 'Резюме отправлено'), ('контакт', 'Контакт'), ('вакансия закрыта', 'Вакансия закрыта'), ('свободен', 'Свободен'), ('запрос на добавление', 'Запрос на добавление')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
