# Generated by Django 2.1.5 on 2019-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0011_auto_20190211_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('intern', 'Intern'), ('techlead', 'Tech Lead'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('none', 'None'), ('arch', 'Arch'), ('teamlead', 'Team Lead')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('контакт', 'Контакт'), ('запрос на добавление', 'Запрос на добавление'), ('свободен', 'Свободен'), ('вакансия закрыта', 'Вакансия закрыта'), ('резюме отправлено', 'Резюме отправлено')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
