# Generated by Django 2.1.5 on 2019-02-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0012_auto_20190211_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='job_opotunity',
            field=models.CharField(choices=[('возможно ищет работу', 'Возможно ищет работу'), ('не ищет работу', 'Не ищет работу')], default='возможно ищет работу', max_length=40, verbose_name='Ищет или нет'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('none', 'None'), ('teamlead', 'Team Lead'), ('intern', 'Intern'), ('senior', 'Senior'), ('middle', 'Middle'), ('arch', 'Arch'), ('junior', 'Junior'), ('techlead', 'Tech Lead')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('запрос на добавление', 'Запрос на добавление'), ('контакт', 'Контакт'), ('резюме отправлено', 'Резюме отправлено'), ('вакансия закрыта', 'Вакансия закрыта'), ('свободен', 'Свободен')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
