# Generated by Django 2.1.5 on 2019-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0013_auto_20190211_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('intern', 'Intern'), ('middle', 'Middle'), ('junior', 'Junior'), ('techlead', 'Tech Lead'), ('arch', 'Arch'), ('senior', 'Senior'), ('teamlead', 'Team Lead'), ('none', 'None')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('свободен', 'Свободен'), ('запрос на добавление', 'Запрос на добавление'), ('в контактах', 'В контактак')], default='свободен', max_length=40, verbose_name='Этап рекрутинга'),
        ),
    ]
