# Generated by Django 2.1.5 on 2019-04-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0017_auto_20190327_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100)),
                ('vacancy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('techlead', 'Tech Lead'), ('middle', 'Middle'), ('arch', 'Arch'), ('senior', 'Senior'), ('teamlead', 'Team Lead'), ('none', 'None'), ('intern', 'Intern'), ('junior', 'Junior')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='project',
            name='name_dev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peopleDB.Developer'),
        ),
    ]
