# Generated by Django 2.1.5 on 2019-04-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0018_auto_20190415_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name_dev',
        ),
        migrations.AddField(
            model_name='developer',
            name='to_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peopleDB.Project', verbose_name='В какую компанию'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('arch', 'Arch'), ('techlead', 'Tech Lead'), ('teamlead', 'Team Lead'), ('intern', 'Intern'), ('senior', 'Senior'), ('none', 'None')], default='none', max_length=20, verbose_name='Уровень'),
        ),
    ]
