# Generated by Django 2.1.5 on 2019-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0019_auto_20190415_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior'), ('teamlead', 'Team Lead'), ('arch', 'Arch'), ('intern', 'Intern'), ('techlead', 'Tech Lead'), ('middle', 'Middle'), ('none', 'None')], default='none', max_length=20, verbose_name='Уровень'),
        ),
    ]
