# Generated by Django 2.1.5 on 2019-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0023_auto_20190423_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('techlead', 'Tech Lead'), ('none', 'None'), ('teamlead', 'Team Lead'), ('middle', 'Middle'), ('intern', 'Intern'), ('senior', 'Senior'), ('junior', 'Junior'), ('arch', 'Arch')], default='none', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='step_recruit',
            field=models.CharField(choices=[('CV отправлено', 'CV отправлено'), ('none', 'None')], default='none', max_length=20, verbose_name='В процессе'),
        ),
    ]
