# Generated by Django 2.1.5 on 2019-04-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleDB', '0026_auto_20190427_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='rank_position',
            field=models.CharField(choices=[('arch', 'Arch'), ('intern', 'Intern'), ('techlead', 'Tech Lead'), ('middle', 'Middle'), ('teamlead', 'Team Lead'), ('none', 'None'), ('senior', 'Senior'), ('junior', 'Junior')], default='none', max_length=20, verbose_name='Уровень'),
        ),
    ]
